snoke_o_auth:
  github:
    client_id:
    redirect_uri: 'auth/github'
    secret:
  google:
    client_id:
    redirect_uri: 'auth/google'
  facebook:
    client_id:
    secret:
    redirect_uri: '/auth/facebook'