snoke_o_auth:
  google:
    apiKey:
    success: '/success/$token'
    style:
      theme: 'outline'        # outline / fill_blue / filled_black
      width: '120px'          # width in pixel
      locale: 'en_EN'	      # locale
      type: 'standard' 	      # standard / icon
      size: 'medium' 	      # small / medium / large
      text: 'signin'	      # signin / continue_with / signup_with / signin_with
      shape: 'rectangular'    # rectangular / pill / circle / square
      logo_alignment: 'left'  # left / center